tap "eugenmayer/dockersync"
tap "homebrew/core"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/bundle"
brew "antigen"
brew "awscli"
brew "composer"
brew "git"
brew "inetutils"
brew "node@8", link: true
brew "mysql@5.7", link: true
brew "php@7.1"
brew "ruby"
brew "sqlite"
brew "tree"
brew "vim"
brew "wget"
brew "yarn", args: ["without-node"]
brew "eugenmayer/dockersync/unox"
brew "zsh"
brew "htop"
cask "1password"
cask "font-awesome-terminal-fonts"
cask "docker"
cask "google-chrome"
cask "iterm2"
cask "ngrok"
cask "sequel-pro"
cask "slack"
cask "spectacle"
cask "tunnelblick"
