tap "homebrew/core"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/bundle"
tap "nexeck/homebrew-tmuxinator"
brew "antigen"
brew "awscli"
brew "composer"
brew "git"
brew "htop"
brew "inetutils"
brew "jq"
brew "nexeck/homebrew-tmuxinator/tmuxinator"
brew "node@8", link: true
brew "mysql@5.7", link: true
brew "php@7.1"
brew "ruby"
brew "sqlite"
brew "tmux"
brew "travis"
brew "tree"
brew "vim"
brew "wget"
brew "yarn", args: ["without-node"]
brew "zsh"
cask "1password"
cask "font-awesome-terminal-fonts"
cask "docker"
cask "google-chrome"
cask "iterm2"
cask "ngrok"
cask "sequel-pro"
cask "slack"
cask "tunnelblick"
