tap "homebrew/core"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/bundle"
tap "universal-ctags/universal-ctags"
brew "awscli"
cask "font-menlo-for-powerline"
brew "git"
cask "google-chrome"
brew "gnupg"
brew "inetutils"
cask "iterm2"
brew "jq"
brew "mysql-client@5.7", link: true
brew "php@7.4"
brew "php@8.0"
brew "php"
brew "pinentry-mac"
brew "ruby@2.7"
brew "shellcheck"
cask "slack"
brew "sqlite"
brew "tmux"
brew "universal-ctags", args: ['HEAD']
brew "vim"
brew "zsh"
cask "1password"
