# logfilename          [owner:group]    mode count size when  flags [/pid_file] [sig_num]
/Users/martijngastkemper/Library/Logs/com.martijngastkemper/theme-switcher.out.log                     644  5    100  *       N
/Users/martijngastkemper/Library/Logs/com.martijngastkemper/theme-switcher.err.log                     644  5    100  *       N
/Users/martijngastkemper/Library/Logs/com.martijngastkemper/opencode-update.out.log                    644  5    100  *       N
/Users/martijngastkemper/Library/Logs/com.martijngastkemper/opencode-update.err.log                    644  5    100  *       N
