" Vundle setup {{{{

    set nocompatible              " be iMproved, required
    filetype off                  " required

    " set the runtime path to include Vundle and initialize
    set rtp+=~/.vim/bundle/Vundle.vim
    call vundle#begin()

    " let Vundle manage Vundle, required
    Plugin 'VundleVim/Vundle.vim'
    Plugin 'airblade/vim-gitgutter'
    Plugin 'christoomey/vim-tmux-navigator'
    Plugin 'ctrlpvim/ctrlp.vim'
    Plugin 'dkarter/bullets.vim'
    Plugin 'editorconfig/editorconfig-vim'
    Plugin 'FelikZ/ctrlp-py-matcher'
    Plugin 'lumiliet/vim-twig'
    Plugin 'ludovicchabant/vim-gutentags'
    Plugin 'machakann/vim-highlightedyank'
    Plugin 'shawncplus/phpcomplete.vim'
    Plugin 'StanAngeloff/php.vim'
    Plugin 'tpope/vim-commentary'
    Plugin 'tpope/vim-surround'
    Plugin 'tpope/vim-repeat'

    call vundle#end()
    filetype plugin on

" }}}}

" Gutentags {{{{

    let g:gutentags_cache_dir = "~/.cache/vim/tags"
    let g:gutentags_ctags_extra_args = ["--tag-relative", "--recurse", "--fields=+aimlS", "--languages=php,squirrel", "--output-format=e-ctags"]
    let g:gutentags_modules=['ctags'] " This line must called before gutentags#statusline "

" }}}}

" GUI {{{{{

    " Enable syntax highlighting
    syntax on

    " Enable true color (Ghostty supports it)
    set termguicolors

    " Auto-switch background based on tmux theme (set by dark/light scripts)
    if $TMUX_THEME == "light"
        set background=light
    else
        set background=dark
    endif

    " Readable on both white and near-black backgrounds
    highlight LineNr guifg=#808080 ctermfg=244
    highlight Comment guifg=#808080 ctermfg=244
    highlight Statement guifg=#cc8844 ctermfg=179
    highlight Type guifg=#55aa55 ctermfg=71
    highlight PreProc guifg=#9955cc ctermfg=98
    highlight Identifier guifg=#5599cc ctermfg=68
    highlight Special guifg=#55aaaa ctermfg=73
    highlight Constant guifg=#cc5555 ctermfg=167

    " status line
    set statusline=%f\ %y\ %m\ %r\ Line:\ %l/%L\ Col:\ %c\ Buf:\ #%n\ %{gutentags#statusline()}
    set laststatus=2
    set showcmd

    " linenumbers
    set number
    set relativenumber

    set scrolloff=5

    " allow backspacing over everything in insert mode
    set backspace=indent,eol,start

    " Show a column in Markdown files at the maximum line length
    augroup markdown_colorcolumn
        autocmd!
        autocmd FileType markdown setlocal colorcolumn=80
    augroup END

" }}}}

" Mappings {{{{

    let mapleader = ","

    " For when you forget to sudo.. Really Write the file.
    cmap w!! w !sudo tee % >/dev/null

    " quick access to $MYVIMRC for editing and reloading the vimrc file
    nnoremap <leader>ev :vsplit $MYVIMRC<cr>
    nnoremap <leader>sv :source $MYVIMRC<cr>

    " fast saving
    nnoremap <leader>w :w!<cr>

    " List open buffers and type the id to navigate to it
    nnoremap § :ls<cr>:b

    " yank from the cursor to the end of the line, to be consistent with C and D.
    nnoremap Y y$

" }}}}

" Search {{{{

    set ignorecase
    set smartcase
    set hlsearch
    set incsearch

" }}}}

" Misc {{{{

    " no swap files
    set noswapfile

    " Allow switching from unsaved buffer to another buffer
    set hidden

    " Enter opens tag
    augroup tag_navigation
        autocmd!
        autocmd BufRead,BufNewFile * if &l:modifiable | nnoremap <buffer> <CR> :exec("tag ".expand("<cword>"))<CR> | endif
    augroup END

" }}}}

" ctrlp.vim {{{{

    " Ignore some files and folders
    set wildignore+=*.o,*.obj,*.jpg,*.jpeg,*.png,*.gif,*.ser,.git,.idea
    set wildignore+=node_modules

    " Use ctrlp-py-matcher for improved performance
    let g:ctrlp_match_func = { 'match': 'pymatcher#PyMatch' }

    " Allow dotfiles like .env and .env.template
    let g:ctrlp_dotfiles = 1

" }}}}

" Bullets.vim {{{{

    let g:bullets_enabled_file_types = [
        \ 'markdown',
        \ 'text',
        \ 'gitcommit',
        \ 'scratch'
        \]

" }}}}

" gitgutter {{{{

    " Update after 100ms instead of the default 4000ms
    set updatetime=100

" }}}}
