set-window-option -g status-left-style 'fg=#000000,bg=#5c9cf5'

set-window-option -g status-right-style 'fg=gray,bg=#000000'

set-window-option -g window-status-current-style 'fg=#000000,bg=#5c9cf5'

# Set inactive/active window styles
set -g window-style 'fg=lightgray,bg=#000000'
set -g window-active-style 'fg=white,bg=#000000'

set -g status-style 'fg=lightgray,bg=#000000'

set -g pane-border-style 'fg=#282828,bg=#000000'
set -g pane-active-border-style 'fg=#5c9cf5,bg=#000000'

setenv -g TMUX_THEME dark
