#!/bin/sh

# The following is based on https://gist.github.com/sindresorhus/7996717
changed_files=$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD)

check_run() {
    if echo "$changed_files" | grep --quiet "$1";
    then
        echo ""
        echo " 👉  $1 changed! You may want to $2!"
    fi
}

check_run bower.json "run bower install"
check_run composer.json "run composer install"
check_run composer.lock "run composer install"
check_run docker-compose.*yml "run docker-compose build"
check_run .env.example "update your environment variables"
check_run env.template "update your environment variables"
check_run package.json "run yarn install"
check_run package-lock.lock "run npm install"
check_run pnpm-lock.yaml "run pnpm install"
check_run yarn.lock "run yarn install"
