#!/bin/bash

PROJECT=$(pwd)
FILES=$(git diff --cached --name-only --diff-filter=ACMR HEAD "*.php"| sed 's| |\\ |g')

[ -z "$FILES" ] && exit 0

echo "Checking PHP Lint..."

for FILE in $FILES
do

  if php -l -d display_errors=0 "$PROJECT"/"$FILE";
  then
      echo "Fix the error before commit."
      exit 1
  fi
  FILES="$FILES $PROJECT/$FILE"
done

# Determine wether this project contains phpcs
[ ! -f ./vendor/bin/phpcs ] && exit 0

STANDARDS_FILE=""
if [ -f ./vendor/grrr-amsterdam/garp3/phpcs.xml ]
then
  STANDARDS_FILE="./vendor/grrr-amsterdam/garp3/phpcs.xml"
fi

echo "Running Code Sniffer..."
./vendor/bin/phpcs --standard=$STANDARDS_FILE --colors --encoding=utf-8 -n -p "$FILES"
