name: Linting

on:
  push:

jobs:
  actionlint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      - run: make installed_brew
      - run: brew install actionlint
      - run: actionlint -color

  editorconfig-checker:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      - run: make installed_brew
      - run: brew install editorconfig-checker
      - run: editorconfig-checker

  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: make installed_shellcheck
      - run: shellcheck -- bin/* *.sh git_template/hooks/* bash_aliases

  skills-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Cache token counts
        id: token-counts
        uses: actions/cache@v5
        with:
          path: .skills-lint-cache/tokens.json
          key: token-counts
      - run: make install_skills_lint
      - run: skills-lint --quiet

  zunit:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      - run: make installed_brew
      - run: brew install zsh
      - run: brew trust molovo/revolver
      - run: brew tap molovo/revolver
      - run: brew install zunit-zsh/zunit/zunit
      - run: |
          # Make zunit and revolver available in the PATH
          export PATH="./bin:$PATH"
          # Fix for revolver to make it work in a non interactive shell
          export TERM="dumb"
          zunit
