name: Linting

on:
  push:

jobs:
  actionlint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      - run: brew install actionlint
      - run: actionlint -color

  editorconfig-checker:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      - run: brew install editorconfig-checker
      - run: editorconfig-checker

  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: shellcheck -- bin/* *.sh git_template/hooks/* bash_aliases

  zunit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: sudo apt install -y zsh
      - run: make install_zunit
      - run: |
          # Make zunit and revolver available in the PATH
          export PATH="./bin:$PATH"
          # Fix for revolver to make it work in a non interactive shell
          export TERM="dumb"
          zunit
